### ISSUE TITLE
Passing in fully configured matrix file into binary for a non-preconfigured chain fails

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/ibctest#263]
Between the `chain name`, `chain spec name`, `chain config name` and "registered chain labels", something is getting tangled.

Example of failing config (chihuahua is fully configured in matrix and not a pre-configured chain):
https://github.com/strangelove-ventures/ibctest/blob/dan/matrix-fix/cmd/ibctest/deleteme/example_matrix_custom2.json

Yielded Error:
```
--- FAIL: TestConformance (0.02s)
    ibctest_test.go:201: View chain and relayer logs at /Users/dan/.ibctest/logs/ibctest.log
    --- FAIL: TestConformance/chain_pairs (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x5405e77]

goroutine 67 [running]:
testing.tRunner.func1.2({0x5600d00, 0x6fe22b0})
	/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x5600d00, 0x6fe22b0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/strangelove-ventures/ibctest.(*BuiltinChainFactory).Name(0xc0012e1360)
	/Users/dan/go/src/github.com/strangelove-ventures/ibctest/chainfactory.go:137 +0x97
```

**Comment by boojamya** [comment]
FIX WIP:

https://github.com/strangelove-ventures/ibctest/blob/e7538a9892b3390de885261c69b2d0a657291305/chainspec.go#L71-L102

NOTE: 
https://github.com/strangelove-ventures/ibctest/blob/e7538a9892b3390de885261c69b2d0a657291305/ibc/types.go#L95-L98
